### PR TITLE
Support nested masgn block args, closes #50

### LINKED ISSUE #50: mishandles nested `masgn` nodes in block args
```ruby
str = 'a { |(b, (c, d))| }'
ast = RubyParser.new.parse(str)
# => s(:iter, s(:call, nil, :a), s(:args, s(:masgn, :b, s(:masgn, :c, :d))))
Ruby2Ruby.new.process(ast)
# => "a { |(b, masgn, c, d)| }"
```

```ruby
str = 'a { |((b))| }'
ast = RubyParser.new.parse(str)
# => s(:iter, s(:call, nil, :a), s(:args, s(:masgn, s(:masgn, :b))))
Ruby2Ruby.new.process(ast)
# => RuntimeError (no clue: s(:masgn, :b))
```

### PR DESCRIPTION
**Pull request by jaynetics**

### CODE REVIEW

**Comment by janosch-x** [comment]
the second commit fixes some more cases as shown in the updated test. i've left the first commit unsquashed for comparison for now.

obviously the ivar isn't exactly pretty. the code is arguably more readable than the original now, but i'll understand if you want to avoid adding state like this. maybe `#context` can be used instead?

**Comment by zenspider** [comment]
OK. Finally getting on this (sorry). Since I took so long, it didn't apply but I patched in your final version wholesale. I'm not sure about whether to use context or not.

I've done one refactoring to help with that:

```ruby
  def with_masgn_array
    @masgn_array_depth ||= 0 # TODO: remove ivars

    @masgn_array_depth += 1
    res = yield
    @masgn_array_depth -= 1

    parenthesize = @masgn_array_depth > 0

    [res, parenthesize]
  end
```

BUT... your tests don't actually hit this nesting case? I need to poke at that more.

**Comment by zenspider** [comment]
Damnit. I wrote up this whole big thing and now it's gone.

I've reworked the code a bit. Part of the problem was that the tests didn't cover the nested + array scenario, so I added this test:

```ruby
  def test_multiple_nested_masgn_array
    inn = s(:masgn,
            s(:array,
              s(:masgn, s(:array, s(:lasgn, :a), s(:lasgn, :b))),
              s(:lasgn, :c)),
            s(:to_ary, s(:call, nil, :fn)))
    out = "(a, b), c = fn"

    assert_parse inn, out
  end
```

Then I went through a couple different refactorings until I settled on this:

```ruby
  def process_masgn(exp) # :nodoc:
    # s(:masgn, s(:array, s(:lasgn, :var), ...), s(:to_ary, <val>, ...))
    # s(:iter, <call>, s(:args, s(:masgn, :a, :b)), <body>)
    parenthesize = true

    result = exp.sexp_body.map { |sexp|
      case sexp
      when Sexp then
        if sexp.sexp_type == :array then
          parenthesize = context.grep(:masgn).size > 1
          res = process sexp

          res[1..-2]
        else
          process sexp
        end
      when Symbol then
        sexp
      else
        raise "unknown masgn: #{sexp.inspect}"
      end
    }
    parenthesize ? "(#{result.join ', '})" : result.join(' = ')
  end
```

Which... I _think_ is correct? I'd love some extra eyeballs on it.

**Comment by zenspider** [comment]
Done. Thank you!

**Comment by jaynetics** [comment]
> Which... I _think_ is correct? I'd love some extra eyeballs on it.

This whole thing isn't exactly fresh in my head anymore, but it seems fine to me. The solution with context is definitely nicer. 👍

**Pull request closed without merging**
